apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-hello
  namespace: lasample
  labels:
    app: qa-hello
spec:
  selector:
    matchLabels:
      app: qa-hello
  template:
    metadata:
      labels:
        app: qa-hello
    spec:
      containers:
      - name: qa-hello
        image: acgtes/gitops:qa-hellov1.15
